/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eportfolio.main;

/**
 *
 * @author zmc94
 */
public enum LanguageEnum {
	OK,
	CANCEL,
	ERROR,
	YES,
	NO,
	SUBMIT,
	BROWSE,
	CONFIRM,
	DELETE,
	
	PROGRAM_TITLE,
	
	TOOLTIP_NEW_FILE,
	TOOLTIP_OPEN_FILE,
	TOOLTIP_SAVE_FILE,
	TOOLTIP_SAVE_AS_FILE,
	TOOLTIP_EXPORT,
	TOOLTIP_EXIT,
	TOOLTIP_EDIT_VIEW,
	TOOLTIP_VIEW_VIEW,
	TOOLTIP_NEW_PAGE,
	TOOLTIP_REMOVE_PAGE,
	TOOLTIP_REFRESH_PREVIEW,
	TOOLTIP_REMOVE_ELEMENT,
	TOOLTIP_MOVE_UP_ELEMENT,
	TOOLTIP_MOVE_DOWN_ELEMENT,
	
	RADIOBUTTON_EDIT,
	RADIOBUTTON_VIEW,
	
	LABEL_PAGE_SELECTOR,
	
	DIALOG_SAVE_CONFIRMATION,
	DIALOG_SAVE_CONFIRMATION_WARNING,
	DIALOG_SAVE_AS_TITLE,
	DIALOG_CONFIG_SELECT_TITLE,
	DIALOG_CONFIG_SELECT_PROMPT,
	DIALOG_VIEW_EXCEPTION_TITLE,
	DIALOG_VIEW_EXCEPTION_HEADER,
	
	USERHINT_NEW_EPORTFOLIO_CREATED,
	USERHINT_VIEW_EXCEPTION_DETAIL,
	
	ERROR_FAIL_TO_SAVE,
	ERROR_FILE_NOT_FOUND,
	ERROR_IO_EXCEPTION,
	ERROR_PROPERTY_CTEATTION,
	ERROR_CONTENT_CREATION,
	ERROR_FAIL_TO_PREVIEW,
	ERROR_TITLE_DUPLICATION,
	ERROR_FAIL_TO_REMOVE_ELEMENT,
	ERROR_FAIL_TO_MOVE_UP_ELEMENT,
	ERROR_FAIL_TO_MOVE_DOWN_ELEMENT,
	ERROR_ELEMENT_SELECTION,
	ERROR_ELEMENT_NOT_TEXT,
	ERROR_LINK_OVERLAPED,
	ERROR_LINK_NOT_FOUND,
	ERROR_PAGE_NOT_ENOUGH_TO_VIEW,
	
	ERROR_FAIL_TO_CREATE_ELEMENT,
	
	//default names
	TEXT_ELEMENT_DEFAULT,
	TEXT_PROPERTY_DEFAULT,
	TEXT_DEFAULT_PAGE_NAME,
	
	PROMPT_TEXT_ELEMENT,
	PROMPT_IMAGE_ELEMENT,
	PROMPT_IMAGE_ELEMENT_CAPTION,
	PROMPT_IMAGE_ELEMENT_FLOATING,
	PROMPT_VIDEO_ELEMENT,
	PROMPT_VIDEO_ELEMENT_CAPTION,
	PROMPT_SLIDESHOW_ELEMENT,
	PROMPT_HEADING_ELEMENT,
	PROMPT_LIST_ELEMENT,
	
	PROMPT_TEXT_LINK_START_LABEL,
	PROMPT_TEXT_LINK_END_LABEL,
	PROMPT_LABEL_LIST_COMPONENT,
}
